# Generated by Django 4.2 on 2023-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('DiscountPrice', models.FloatField()),
                ('Image_Url', models.CharField(max_length=300)),
                ('Category', models.CharField(max_length=100)),
                ('Barcode', models.CharField(max_length=16)),
                ('EAN', models.CharField(max_length=6)),
            ],
        ),
    ]
