# Generated by Django 4.2 on 2023-04-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimumStockQuantity', models.IntegerField(default=0)),
                ('Class', models.CharField(choices=[('N/A', 'N/A'), ('EXTRA CLASS', 'Extra Class'), ('CLASS 1', 'Class 1'), ('CLASS 2', 'Class 2')], default='N/A', max_length=11)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestBeforeDate', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('activeProduct', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.activeproduct')),
            ],
        ),
    ]
