# Generated by Django 4.2 on 2023-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_stockitem_bestbeforedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('BBD', 'bbd'), ('DAMAGES', 'Damages'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.stockitem')),
            ],
        ),
    ]
