# Generated by Django 4.2 on 2023-04-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_writeoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Inventory.activeproduct')),
            ],
        ),
    ]
